version: '3.4'

services:
  postgres:
    container_name: Postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    restart: unless-stopped

  identity:
    container_name: Identity
    build:
      context: "."
      dockerfile: /Services/Identity/Identity.WebAPI/Dockerfile
    depends_on:
      - postgres
    ports: 
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
    