name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice:
          - Identity
          - Words
          - Achievements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.100'

      - name: Restore dependencies
        run: |
          cd src/Services/${{ matrix.microservice }}
          dotnet restore

      - name: Build and test
        run: |
          cd src/Services/${{ matrix.microservice }}
          dotnet build --configuration Release --no-restore
          dotnet test --configuration Release --no-build
